### ISSUE TITLE
3波対応で1TSなチューナーの設定方法について

### ISSUE THREAD

**Issue by hendecarows** [kaikoma-soft/raspirec#1]
raspirec を DTV02-1T1S-U で動作確認中です。
録画コマンドは px4_drv で recpt1 が動作しますので respirec 自体は動作します。

DTV02-1T1S-U は 3波(GR,BS,CS) 対応ですが最大 1TS のみしか取得できないチューナーで
PT3 等の様に地上波と衛星の TS を同時に取得はできません。

2台の DTV02-1T1S-U を接続している場合、config.rb に GR_tuner_num = 1,BSCS_tuner_num = 1
と設定すれば使えます。しかし、本来、以下の同時録画が可能なのに (2)地上,衛星 の場合しか対処して
くれないようです。その設定では当然だろうと思いますが。

(1)地上,地上
(2)地上,衛星
(3)衛星,衛星

GR = 2, BSCS = 2, Total_tuner_limit = 2 としてやればそれらしい振る舞いの感じはしますが 
(1),(2),(3) 全てに対応するためにはどう設定するのが良いのでしょうか？

**Comment by kaikoma-soft** [comment]
まず raspirec は、私が所有している PT2,Q3U4 のような地デジ、BSCS 分離型のチューナーを
前提として、プログラムの内部構造もそれ従って作られています。
なので、3波一体型で使用することは想定外で、設定だけで対応することは出来ません。

それを承知で使われるならば、 GR = 2, BSCS = 2, Total_tuner_limit = 2 が最善です。
予約状況表でチューナーの数が２倍になる問題はありますが、それを我慢すれば、それ以外の
機能については問題は無い筈です。

**Comment by hendecarows** [comment]
GR = 1, BSCS = 1 だとチューナー数が半減してしまうのでさすがに厳しいなと思っていましたので、Total_tuner_limit が設定可能なおかげでチューナーを有効に活用できそうです。

GR = 2, BSCS = 2, Total_tuner_limit = 2 で使います。

ありがとうございました。
