### ISSUE TITLE
番組検索画面で「無料放送のみ」を指定しても無料放送の番組に絞り込めない

### ISSUE THREAD

**Issue by cohasefall** [kaikoma-soft/raspirec#10]
### 事象
番組検索画面にて「検索対象」の「無料放送のみ」にチェックを入れて検索しても、
検索結果に有料放送の番組が含まれてしまい、正しく無料放送のみの結果にならないようです。

### 確認環境
Windows 10 Home 21H1
Google Chrome 102.0.5005.115

### 原因
https://github.com/kaikoma-soft/raspirec/blob/57d608a8f43806633496b75c47ad1f77804c19e1/src/model/FilterM.rb#L45
上記コードの`params["freeonly"]`が`params["freeOnly"]`になっていないことが原因と思われます。
もし可能でしたら修正をご検討いただけますと幸いです。

**Comment by kaikoma-soft** [comment]
ご指摘ありがとうございます。 
Ver1.3.4 にて修正しましたのでご確認下さい。

**Comment by cohasefall** [comment]
早々にご対応いただきありがとうございます。
修正いただいた内容で問題が解消されたことを確認いたしました。
