### ISSUE TITLE
Ubuntu24.04LTS raspirecTV対応の件

### ISSUE THREAD

**Issue by null110105** [kaikoma-soft/raspirec#11]
Ubuntu24.04LTSにてraspirecTVをインストールしようとしたところ
必要モジュールruby-gtk2がsudo apt installではどうやらインストール出来なくなっているようです
22.04LTSまではリポジトリに登録してあったのか問題なくapt install出来てたのですが……
24.04LTSではruby-gtk3しかsudo apt install出来なくなっていました

raspirec本体の方は問題なく24.04LTSの方でも環境構築出来ました
raspirecTVを使わなくとも別に運用では問題はないのですが、せっかく作って頂いてる視聴アプリが
使えないのも残念ではあります

gtk3対応なり、24.04LTSでのraspirecTV動作の程お願いしたいのですが　以上

**Comment by kaikoma-soft** [comment]
ご指摘ありがとうございます。　確かに 24.04LTS で ruby-gtk2 が使えないようです。
そこで、 gtk3 対応の作業中ですが、簡単には済まない感じなので、しばらくお待ち下さい。

**Comment by kaikoma-soft** [comment]
gtk3 対応の raspirecTV を Ver1.4.3 としてリリースしました。

**Comment by null110105** [comment]
対応ありがとうございます　Ubuntu24.04LTSでraspirecTV動作確認出来ました
今後共また何かありましたらよろしくお願い致します　本当にありがとうございました
