### ISSUE TITLE
Raspberry Pi OS 新規録画環境導入の件

### ISSUE THREAD

**Issue by null110105** [kaikoma-soft/raspirec#12]
作者さん御提供のraspirec何時も愛用させて頂いております
現状旧Raspbian（Buster)にてraspirec環境を安定運用しておりました
それから年月も経ちRpiのOS環境もかなり変わりOSから新規環境を構築しようと
しましたがトラブルに遭遇しましたのでご報告させて頂きます

ハード　ラズパイ4 4G版
導入OS Raspberry Pi OS 最新版bookworm64bit及び32bit、bullseye64bitの三種
いずれもRaspberry Pi ImagerにてSDインストール
録画記録メディアは外付けHDD

※32bit bookwormは32bitOSを謳いつつもカーネルのみ64bitデフォに変更されてるので
/boot/firmware/config.txtにarm_64bit=0 を追記し32bitカーネルに戻した後環境構築

px4_drvはtsukumijimaフォークをdkmsインストール（つくみ氏debファイルは使用せず）
libarib25はstz2012氏版、recpt1及びepgdumpは作者さんkaikoma-softフォーク使用
上記の環境で各々recpt1をコマンドラインで録画出来るのを確認した後raspirecインストール

上記全ての環境でraspirecを起動したところ、epg取得にlog取得など正常に稼働し
mpvモニタにraspirecTVアプリも正常稼働しました

しかし上記3環境（bullseye64bit及びbookworm64bit32bit）全てにおいていざ録画
しようとすると

09:39:11: 録画準備開始 日曜美術館　印象派１５０年　美の革命　パリ・オルセー美術館【字】
09:39:11: 録画開始の為 EPG取得を中止しました。
09:39:13: Ch=CS2    : ins=> 661, upd=>   4, same=> 897 : 1.56 Sec (Tx 0.50 Sec)
09:39:14: 終了予定 = 2024-06-23 09:45:05 +0900 : 日曜美術館　印象派１５０年　美の革命　パリ・オルセー美術館【字】
09:39:16: Ch=CS4    : ins=>2363, upd=>  10, same=>3147 : 3.36 Sec (Tx 1.03 Sec)
09:39:16: kill for retry 4605
09:39:16: 録画開始失敗: 日曜美術館　印象派１５０年　美の革命　パリ・オルセー美術館【字】 retry 1
09:39:17: 終了予定 = 2024-06-23 09:45:05 +0900 : 日曜美術館　印象派１５０年　美の革命　パリ・オルセー美術館【字】
09:39:21: kill for retry 4609
09:39:21: 録画開始失敗: 日曜美術館　印象派１５０年　美の革命　パリ・オルセー美術館【字】 retry 2
09:39:21: timer:childWait() pid=4605 Terminated
09:39:21: timer:childWait() pid=4609 Terminated
09:39:22: 終了予定 = 2024-06-23 09:45:05 +0900 : 日曜美術館　印象派１５０年　美の革命　パリ・オルセー美術館【字】　

……のように以降Retryを9回繰り返し後失敗してしまいます　3環境全てがこの状態です

念のため安定環境であるRaspbian環境のSDを刺しなおして録画してみたところ
問題なく録画出来ています

全く理解出来ないのがmpvモニタやRaspirecTVアプリでリアルタイム視聴が全ての
環境で出来ている事です　コマンドラインでもrecpt1単体で全ての環境で録画も出来てます
外付けHDDに準備しているraspirec_dataもdb、json、logファイルの中身は全て問題なく更新されてます
しかしraspirecでいざ録画しようとすると失敗を繰り返すばかりで録画が一切出来ません
不思議なことに録画のみ失敗するのです

Raspberry Pi OSに変わってから仕様が変更されたのでしょうか？
それとも当方だけの問題でしょうか？　残念ながら当方の実力では原因究明に
至れませんでした　もし作者さんなり誰かここを見てらっしゃる方で心当たりが
あるという方は情報提供をお願いしたく思います　以上

**Comment by kaikoma-soft** [comment]
すみません。当方の OS は buster 32bit なので確認が取れないのですが、
仮説としては、下記のものが考えられます。

raspirec は録画開始時に、出力ファイルのサイズを監視していてサイズが増えない
場合、異常とみなして retry をするようにしています。
それが OS が変わったことにより、多少時間が掛かる様になり、retry に引っ掛かる
ようになったのかもしれません。

なので、もし可能であれば raspirec/src/model/Recpt1.rb の 174 行目の
sleep時間を 0.2秒から 1秒に変更して試してみて下さい。
waitT は通常 2 なので、監視時間は 1 秒 x 2 x 5 = 10秒 になります。

    (waitT * 5 ).times do |n|
      if test(?f, outfname )
        size = File.size( outfname )
        break if size > 1024
      end
      sleep(0.2)   #  ここを sleep(1) に変更
    end

ちなみに、チューナーは何をお使いでしょうか？

**Comment by null110105** [comment]
作者さんからご指摘をお受けしたので早速ソースを改変し
sleep(0.2) から sleep(1) に変更してraspirecを立ち上げてみました
がretryを繰り返して録画失敗は変わらずでした

尚チューナーはW3U4を使用しております
ラズパイ4 の4Gにつないでおり今そのラズパイから書き込みさせて頂いております
使用OSはbookwormの32bit版です　他の64bit版は同一SDを消去しつつ色々と
試して来た関係上直ぐには環境を準備できません　申し訳ありません
尚、同OS上でmpvモニタにraspirecTVも問題なく立ち上がっております

**Comment by kaikoma-soft** [comment]
お手数をおかけしますが、以下の事の確認をお願いします。
 ・config.rb 中の TSDir の値は何ですか？
 ・そのディレクトリは存在していますか？
 ・そのディレクトリは、raspirec のプロセスのオーナーがファイルを書く事が可能になっていますか？

**Comment by null110105** [comment]
config.rbの内容は下記の通りです

BaseDir    = ENV["HOME"] + "/raspirec"
#DataDir    = ENV["HOME"] + "/raspirec_data"
DataDir    = "/media/pi/ボリューム" + "/raspirec_data"
TSDir      = DataDir + "/TS"
DBDir      = DataDir + "/db"
SrcDir     = BaseDir + "/src"

上記の記述はRaspbian(Buster)時代のものをそのまま持って来ております
現状の設定でTSフォルダ以外のdbフォルダやjosnフォルダにlogフォルダへ各種データ
ファイルは問題なくbookwormの32bit版であっても書き込まれております
他の64bitOS版でも同様でした
尚同一設定にて安定環境であるBusterではTSフォルダに録画ファイルとpacketchkファイルが
ちゃんと記録されておりました

尚raspirecプロセスのオーナーがファイル書き込み、については特段意識しておりませんでした　同外付けHDDはbuster時代からのをそのまま流用しており旧環境では
問題なく録画出来ておりましたので特段の設定は致しておりません

**Comment by kaikoma-soft** [comment]
流用したから問題ない筈。ではなく流用したから問題が出る場合があります。
OSを新規にインストールして、旧OSで使っていたファイルシステムをマウントする場合
user名ではなく、uid,gid の一致が問題になりますが、そこはクリアされていますか？

なので下記のコマンドを実行した結果を教えて下さい。
% id
% ls -ld "/media/pi/ボリューム/raspirec_data/TS"
% sudo -u XXXX touch  "/media/pi/ボリューム/raspirec_data/TS/test.file"
  ( XXXX には、raspirec を実行しているユーザー名、自分の場合は touch 以降 )
% ls -l "/media/pi/ボリューム/raspirec_data/TS"

**Comment by null110105** [comment]
pi@raspberrypi:~ $ id
uid=1000(pi) gid=1000(pi) groups=1000(pi),4(adm),20(dialout),24(cdrom),27(sudo),29(audio),44(video),46(plugdev),60(games),100(users),102(input),105(render),106(netdev),115(lpadmin),993(gpio),994(i2c),995(spi)

pi@raspberrypi:~ $ ls -ld "/media/pi/ボリューム/raspirec_data/TS"
drwxr-xr-x 1 pi pi 0  6月 23 16:23 /media/pi/ボリューム/raspirec_data/TS

pi@raspberrypi:~ $ sudo -u pi touch "/media/pi/ボリューム/raspirec_data/TS/test.file"
pi@raspberrypi:~ $ ls -I "/media/pi/ボリューム/raspirec_data/TS"
Bookshelf  epgdump    px4_drv   recpt1       ダウンロード  ドキュメント  音楽  公開
Desktop    libarib25  raspirec  tspacketchk  テンプレート  ビデオ        画像

※追記 touchコマンド実行後　外付けHDDTSフォルダに0バイトのtest.fileが出来ておりました

尚、当方も外付けHDDに問題があるのではと前日に思い至っており、config.rbファイルの
#DataDir = ENV["HOME"] + "/raspirec_data"
DataDir = "/media/pi/ボリューム" + "/raspirec_data"　部分を

デフォルトの
DataDir = ENV["HOME"] + "/raspirec_data"　に戻してホームフォルダにraspirec_data
フォルダを作り直して新規にTSフォルダやdbフォルダ等を設置して録画できるか
試しております　結果外付けHDDを一切使わず、その場合であっても録画はretryを繰り返して失敗したことを遅ればせながら追記させていただきます

尚当方、今日夕刻より所要にて外出致しますので、さらなる対応がある場合
申し訳ありませんが後日余裕が出来た時間に返答させて頂きます事を何卒
ご容赦のほどよろしくお願いいたします

**Comment by kaikoma-soft** [comment]
Raspberry Pi OS Lite 64-bit bookworm での動作検証を行ってみました。

手順の詳細は https://kaikoma-soft.github.io/src/raspirec_install_2024.html
に書きましたが、結果は問題ありませんでした。

従って普通にインストールすれば使えると思いますので、本件は close させていただきます。
