### ISSUE TITLE
issue #12についてお詫びとご報告

### ISSUE THREAD

**Issue by null110105** [kaikoma-soft/raspirec#13]
今回大変な労力を以て新OSでの検証までして頂き本当にありがとうございました
当方の方でも進展がありましたのでご報告申し上げます

SDカードも32ギガのものを新調し新規に64bit bookwormをインストールし一から環境構築を致しました
px4_drv以下の導入はissue #12と同一です

同環境でも、当初はやはり外付けHDDは件の如くTSディレクトリでの録画データ記録は不可でした
しかしながらこれまた＃12でもご報告申し上げました通りその他のlog、db、josnディレクトリには
raspirec起動後から問題なく各種ファイルが生成され記録され続けていたので、TSディレクトリとの違いを
再度考える事にしました

各logやらdb、josnディレクトリは作者さんが予め設定していた各種ファイルが記録されていきます
そしてそのどれもが1バイト文字（英数字）のみのファイル群であるという事です

本命の録画データはBusterでも散々記録してきましたがかな漢字を含む2バイトコード文字をファイル名
に持ったデータです

更に外付けHDDを接続した際、自動でデフォルトに割り当てられるmountディレクトリパスは

"/media/pi/ボリューム"　でありconfig.rbにおいても

DataDir    = "/media/pi/ボリューム" + "/raspirec_data"　と登録していました

新OSであるbullseyeやbookwormになって、そこら辺の扱いが旧OS Busterより条件が厳しくなっているのでは？
と思い直し、デフォルトでの"ボリューム"という2バイト文字列を混ぜたディレクトリパスを止め

ユーザーサイドにて全て一バイト文字列ディレクトリパスのHDDマウントポイントを作り、そこにマウントし直す
事にしました

DataDir	   = "/mnt/hdd" + "/raspirec_data"

と/mnt/ディレクトリにhddディレクトリをmkdirし、そこに外付けHDDをマウントし直してraspirecを
再度起動し直してみました

今度は問題なく本命の録画も記録され、packetchkも行われて両ファイルがちゃんと記録されました

勿論、上記のストーリーとは全く違う要因で録画ファイルが記録出来ず、偶々別マウントし直したので記録出来た
という可能性もない訳ではないのですが……

取り合えず課題である録画ファイルの記録が出来なかった件に関してはこれを以て解決とし当方では当面の間これにて運用して行こうと考えております

となると矛盾するのが当方が＃12にて主張した

デフォルトの
DataDir = ENV["HOME"] + "/raspirec_data"　に戻してホームフォルダにraspirec_data
フォルダを作り直して新規にTSフォルダやdbフォルダ等を設置して録画できるか
試しております　結果外付けHDDを一切使わず、その場合であっても録画はretryを繰り返して失敗したことを遅ればせながら追記させていただきます

の部分です　各種テスト中確かに同ホームディレクトリに直接/raspirec_dataを置いて録画を実行してみた
所、録画失敗してしまった　と強く記憶していたのですが……

再度同上のデフォルト条件にて新規64bit bookworm環境でraspirecを実行したところスンナリと録画された
のにはショックを受けました

結局当方の勘違いで作者さんにも大変な労力と検証を行わせてしまいました
当方もホームディレクトリで録画失敗だと思いこまず、ちゃんと録画出来ていたと最初から認識していれば
外付けHDD周りに最初から原因究明努力を集中して解決に動く事が出来たはずで周囲にも誤った情報でご迷惑をお掛けせずに
済んだのにと、反省しきりであります

という事で当方も解決をみましたので改めてご報告とご迷惑をお掛けしたことを深くお詫びさせて頂きたく思います
本当にありがとうございました　以上

**Comment by kaikoma-soft** [comment]
無事に動作するようになって良かったです。
