### ISSUE TITLE
[要望][提案] 番組表のサイズを動的に変更したい

### ISSUE THREAD

**Issue by yaminav** [kaikoma-soft/raspirec#2]
番組表を見ていて
* もっと詳細に見たい
* おおまかでいいから広く見たい

とか思うことがあります。

src/views/prg_tbl.rb の @hour_pixel の値を変更した上で、
その他->config->プログラムの再起動 することで変更はできるのですけど、
UI上から動的に変更できると便利じゃないかな、と思いました。
もしよろしければご検討ください。

**Comment by kaikoma-soft** [comment]
提案ありがとうございます。
検討してみた所、面白そうなので実装してみました。
ver 0.3.0 です。　お試しください。

**Comment by yaminav** [comment]
おお！1時間のピクセル数だけでなく、他にも細かいオプションが追加されてる！
ありがとうございます、とても使い勝手よくなりました！
