### ISSUE TITLE
[要望][提案]フィルター/自動予約の条件に、番組長が欲しい

### ISSUE THREAD

**Issue by yaminav** [kaikoma-soft/raspirec#3]
私がよく使う録画方法で、
1. 「地上波の映画全部」を列挙するフィルターを作っておく
2. 気が向いたときにフィルター一覧を表示
3. その中から面白そうな番組を録画指定

とかやるのですが、 "○○公開記念特番" のような5分番組がたくさんヒットするのが困ってます。
1時間以上の番組だけ列挙する、みたいな条件指定ができると快適になるのではないかと思いました。
フィルター/自動予約の条件に、番組長の追加、の検討をおねがいいたします。

**Comment by kaikoma-soft** [comment]
検索項目に放送時間（番組長）を Ver0.3.1. で追加してみました。
お試しください。

**Comment by yaminav** [comment]
ありがとうごさいます！映画番組の検索がとても快適になりました。

検索で扱う条件が増えたらDBのマイグレーションが必要になったりとかで
実装面倒かもなあ、と心配していたのですけど、時短フラグの未使用ビット部分を
利用することで、DBのサイズ増やさずに機能追加したのですね。お見事！
