### ISSUE TITLE
[要望][提案]番組検索時の検索文字列生成をカスタマイズしたい

### ISSUE THREAD

**Issue by yaminav** [kaikoma-soft/raspirec#4]
番組表->なにか番組をクリック->ダイアログの自動予約をクリック
で、番組検索の画面に飛びます。この時、
- 題名は、番組名を commlib.rb::deleteOptStr でオプション文字列削除したもの
- 検索文字列は、そこから commlib.rb::deleteNum で話数などを削除したもの

になっているかと思います。処理としてはここ。
https://github.com/kaikoma-soft/raspirec/blob/master/src/views/search.rb#L57-L58

上記の文字列処理をカスタマイズしたいです。
具体的には `検索文字列末尾の「」で括られたサブタイトルを自動的に除去する` をやりたいです。
ただ、この辺りは番組によってフォーマットが変わるし、人によって好みもあるかと思うので、
deleteOptStrやdeleteNum相当の処理内容が config.rb に書けて、
各自でカスタマイズできるようになってるといいな、と思いました。

**Comment by kaikoma-soft** [comment]
確かにカスタマイズ出来たほうが便利ですね。と言う訳で実装してみました。　Ver0.3.3 です。
config.rb.sample 中のTitleRegex、SearchStringRegex の部分を ~/.config/raspirec/config.rb にコピー
して、カスタマイズして下さい。

**Comment by yaminav** [comment]
動作確認ばっちりです。
上に書いてる `「」で括られたサブタイトルを自動的に除去` も入れといてもらえたんですね。
4月の新番組録画登録の手間がだいぶ減りました、ありがとうございます！
