### ISSUE TITLE
フィルターの検索結果に録画済みの番組が表示されるとき、予約の欄に×が表示されてしまう

### ISSUE THREAD

**Issue by yaminav** [kaikoma-soft/raspirec#5]
フィルターの検索結果に、既に録画が終わっている物が出ることがあります。
その場合、予約の部分に"×"が表示されてしまうようです。
あれ？予約失敗した？って心配になるので、直した方が良さそう。

- もう放送が終っている番組は検索結果には表示しない

あるいは、
- "×"ではなく、録画済みであることがわかるような表示にする

がいいですかね。

検索結果のに予約のところに"×"を表示してるのはここかと思われます。
https://github.com/kaikoma-soft/raspirec/blob/master/src/views/fil_res_dsp.rb#L54-L58

**Comment by kaikoma-soft** [comment]
ご指摘ありがとうございます。
現在より古い番組が表示されるのはバグですので Ver.0.3.4 で修正しました。

**Comment by yaminav** [comment]
対応ありがとうございます。
0.3.4 にて、放送が終わった番組はフィルタ結果に出なくなったのを確認しました。

ですが、録画中の番組がフィルタ結果に出る場合には、依然として予約に"×"がつくようです。
これはどうするのがいいでしょうかね。

- 予約× で表示(現状のまま)
- 予約〇 で表示
- 録画中であることを伝える表示
- すでに放送が始まっているものも結果に出さない

といった選択肢が考えられると思います。

**Comment by kaikoma-soft** [comment]
すみません。問題は2つだったのですね。
Ver 0.3.5 で録画中のものが×と誤表示されてしまう件の修正をしました。

**Comment by yaminav** [comment]
> すみません。問題は2つだったのですね。

結果的にはそうなりますが、最初に起票した時点では録画中の問題には気付いておらず、
0.3.4の動作確認中に気付きました。

0.3.5の動作確認はこれからやるところですけど、とりあえず、
https://github.com/kaikoma-soft/raspirec/blob/master/src/views/fil_testrun.rb#L45
にも同等の条件追加が必要な気がします。
そっくりなコードが2か所にあるのはイケてないので、共通化したいですね。

追記
0.3.5で、録画中のものでも 予約〇が表示されることを確認できました。
