### ISSUE TITLE
[要望][提案]TS ファイル名に番組概要が欲しい

### ISSUE THREAD

**Issue by takeuc** [kaikoma-soft/raspirec#6]
下記のようなことをやりたいと考えています。

１）簡単なキーワードで自動予約・録画
２）録画したTSファイルをwindows-PCへ自動転送
３）転送後のファイル名を見て必要なものを選別する

３）にてTSファイル名に番組概要があると、簡単に選別が出来ると思いました。
TSファイル名に番組概要情報の追加の検討をお願いします。

**Comment by kaikoma-soft** [comment]
残念ながら、対応は出来ません。
理由は Linux 場合ファイル名の長さ制限が 256byte であり、番組概要のbyte数はそれを容易に超えてくるからです。
長ければカットして256byteに収める事は可能ですが結構面倒ですし、それで役に立つか不明なのでパスさせて下さい。

**Comment by kaikoma-soft** [comment]
残念ながら、対応は出来ません。
理由は Linux 場合ファイル名の長さ制限が 256byte であり、番組概要のbyte数はそれを容易に超えてくるからです。
長ければカットして256byteに収める事は可能ですが結構面倒ですし、それで役に立つか不明なのでパスさせて下さい。

**Comment by takeuc** [comment]
丁寧なご回答有難うございます。
仰られる通りだと思いますのでクローズさせて下さい。
