### ISSUE TITLE
EPG取得が終了せず、録画が失敗になることがある？

### ISSUE THREAD

**Issue by yaminav** [kaikoma-soft/raspirec#7]
まれに録画失敗になることがあり原因を追っていたのですが、失敗した時に共通している状況は、
`EPG取得開始後、EPG取得終了になる前に録画が始まった時に録画に失敗している`
ように見えました。

その部分のログを以下に抜粋。
```
02:09:22: EPG取得開始
02:10:24: Ch=27     : ins=>  89,upd=>  41,same=> 402
02:11:55: memsize_of_all=6.70 MB ; RSS=32.15 MB ; GCC=6373
02:21:55: memsize_of_all=6.80 MB ; RSS=32.26 MB ; GCC=6373
02:24:48: 録画準備開始 波よ聞いてくれ　♯９「お前を信じない」【アニメイズム】【字】
02:24:53: finish = 2020-05-30 02:55:03 +0900
02:24:53: pid=21693 Terminated
02:24:55: kill for retry 21693
02:24:55: 録画開始失敗: 波よ聞いてくれ　♯９「お前を信じない」【アニメイズム】【字】 retry 1
02:24:56: finish = 2020-05-30 02:55:06 +0900
02:24:56: pid=21696 Terminated
02:24:59: kill for retry 21696
＃...この状況がretry 9まで続く
02:26:07: 録画開始失敗: 波よ聞いてくれ　♯９「お前を信じない」【アニメイズム】【字】
```
ログの他の部分を見ると、EPG取得開始～EPG取得終了は長くても3分程度なのですが、
この時は番組開始まで15分ほどあったにも関わらず、取得終了にならないまま録画が始まっているようでした。
その後もEPG取得終了は出ないまま次のEPG取得開始が始まって、そっちは無事に終了しており、
その後の録画は問題なく行われているように見えました。

**Comment by kaikoma-soft** [comment]
現象からは、チューナーor ドライバーがハングアップして反応しなくなったように見えます。
そうだとすると raspirec からはどうしようもないのですが、幾つか確認したい事が有りますので、
情報提供をお願いします。

* お使いのチューナー、ドライバーは何ですか？
* 上記のものは使用実績がありますか？   (raspirec 以前に別のソフトで問題無く動いていたか？)
* /var/log/syslog に何かメッセージは出てないでしょうか？
* Ch=27 は、「波よ聞いてくれ」 の放送局ですか？
* EPG取得に失敗するような電波状況が悪い局はありませんか？
* EPG取得終了が出ない頻度はどのくらいでしょうか？
  logのあるディレクトリで  % grep "EPG取得" old*/raspirec.log raspirec.log
  すると 開始->終了の対応が取れていないのがわかります。

以上お手数ですがよろしくお願いします。

**Comment by yaminav** [comment]
> お使いのチューナー、ドライバーは何ですか？

チューナー: http://www.plex-net.co.jp/product/px-s1udv2/
ドライバ: http://plex-net.co.jp/plex/px-s1ud/PX-S1UD_driver_Ver.1.0.1.zip
録画コマンド: https://github.com/dogeel/recdvb

上記環境で、Recpt1_cmd = "/usr/local/bin/recdvb" として使用しています。

> 上記のものは使用実績がありますか？ (raspirec 以前に別のソフトで問題無く動いていたか？)

上記のrecdvbコマンド直叩きでの録画は確認済みです。
raspirecは半年ほど使用しており、今回の様な録画失敗が2～3度あったかと思います。

> /var/log/syslog に何かメッセージは出てないでしょうか？

syslogはサイズ0、syslog.1に出ているのは1月のメッセージで本件とは関係なさげでした。

> Ch=27 は、「波よ聞いてくれ」 の放送局ですか？

違いました。Ch=27 は、
`ＮＨＫ総合１・東京 ( ch:27, svid:1024 ) `
で、録画しようとしていたのは、
`ＴＢＳ１ ( ch:22, svid:1048 ) `
になります。

> EPG取得に失敗するような電波状況が悪い局はありませんか？

うーん、ちょっとわかりません。
なにか客観的に確認する方法はあるでしょうか？

> EPG取得終了が出ない頻度はどのくらいでしょうか？
  logのあるディレクトリで % grep "EPG取得" old*/raspirec.log raspirec.log
  すると 開始->終了の対応が取れていないのがわかります。

お！あらためて検索かけてみて気付きました。
```
old_01/raspirec.log:02:09:22: EPG取得開始
old_01/raspirec.log:03:24:54: EPG取得開始
old_01/raspirec.log:03:25:03: EPG取得終了 ins=>   0,upd=>   0,del=>  73,same=>   0
old_01/raspirec.log:03:54:55: EPG取得開始
old_01/raspirec.log:03:55:03: EPG取得終了 ins=>   0,upd=>   0,del=>   9,same=>   0
old_01/raspirec.log:04:24:55: EPG取得開始
old_01/raspirec.log:04:25:03: EPG取得終了 ins=>   0,upd=>   0,del=>  15,same=>   0
old_01/raspirec.log:04:56:14: EPG取得終了 ins=>  89,upd=>  41,del=>   6,same=> 402
```
返ってこなかったわけではなく、約3時間後にEPG取得終了になってますね。

同様の現象が2週間で4回起きてました(ログは2週間前までしか残っていませんでした)
2週間で4回なので毎週でも毎日でもなさそう。
この現象と録画のタイミングが重なった時に失敗になった、ということのようですね。

参考になるかわかりませんが他3回の開始/終了の対応がおかしい箇所も貼っておきます。
なんだか、長時間かかってEPG終了になる時の終了時間がどれも似たような時間になっている？
```
old_03/raspirec.log:02:10:18: EPG取得開始
old_03/raspirec.log:03:24:55: EPG取得開始
old_03/raspirec.log:03:25:03: EPG取得終了 ins=>   0,upd=>   0,del=>  28,same=>   0
old_03/raspirec.log:04:53:21: EPG取得開始
old_03/raspirec.log:04:53:29: EPG取得終了 ins=>   0,upd=>   0,del=>  26,same=>   0
old_03/raspirec.log:04:56:12: EPG取得終了 ins=>   0,upd=>   0,del=>   3,same=>   0

old_03/raspirec.log:02:46:27: EPG取得開始
old_03/raspirec.log:03:46:28: EPG取得開始
old_03/raspirec.log:03:46:37: EPG取得終了 ins=>   0,upd=>   0,del=>  27,same=>   0
old_03/raspirec.log:04:57:11: EPG取得終了 ins=>  21,upd=>   4,del=>  20,same=> 163

old_04/raspirec.log:01:33:56: EPG取得開始
old_04/raspirec.log:02:58:53: EPG取得開始
old_04/raspirec.log:02:59:01: EPG取得終了 ins=>   0,upd=>   0,del=>  66,same=>   0
old_04/raspirec.log:04:56:11: EPG取得終了 ins=>  73,upd=>  14,del=>  30,same=> 435
```

**Comment by kaikoma-soft** [comment]
情報ありがとうございます。一つ仮説を思いつきました。

* 深夜になって放送休止になった局に対して EPG の取得をしようとすると  チューナーがハングアップする。
  早朝になって放送が開始されると、動き出す。

 AM 04:50 位から放送開始の放送局は無いでしょうか？
ただ、raspirec の方でも timeout処理がある筈なので、それが動いていないのが腑に落ちないのですが、実機が無いので確認が難しいです。

それで対症療法ですが、深夜の時間帯に EPG取得をしなければ問題は起きないと予想しましたので、そのような機能を Ver 0.4.1 で追加しました。
config.rb  中に下記のパラメータを追加して下さい。

EpgBanTime     = [ 2, 3, 4, 5 ]   # ２時から6時未満を EPG取得禁止とする。

これで経過観察をお願いします。

**Comment by yaminav** [comment]
> AM 04:50 位から放送開始の放送局は無いでしょうか？

なるほど。その条件に該当しそうなのは、

- ＮＨＫＥテレ１東京 ( ch:26, svid:1032 ) 
毎晩1時前後に放送終了、5:00～5:30開始

- ｔｖｋ１ ( ch:18, svid:24632 ) 
毎晩2:30～3:30に終了、4:30～5:00開始

の2局でした。

> これで経過観察をお願いします。

ありがとうございます。試してみますね。

ところで、上記でも `放送休止になった局に対して EPG の取得` で成功している例はありますし、
その条件だともっと発生頻度が高くなってそうな気がします。
なので、 `EPG取得している最中に放送休止になるとハングアップ` 、辺りではないかと予想。

**Comment by kaikoma-soft** [comment]
とりあえず、ここは close とさせて下さい。
しばらくして駄目だった場合は、reopen か new issue して下さい。
