### ISSUE TITLE
自動予約/フィルタの数が増えると探しにくい

### ISSUE THREAD

**Issue by yaminav** [kaikoma-soft/raspirec#8]
予約一覧や録画一覧は日時順に並んでいるからいいのですけど、
自動予約やフィルタは、数が多くなってくると探しにくいです。

以下を見るに、どうやら文字列順でソートしているようなのですけど、
https://github.com/kaikoma-soft/raspirec/blob/master/src/views/fil_list.rb#L75
実際に使用してみると、
ひらがな->カタカナ->漢字->アラビア数字->英字
の順に並んでいたりしていまいち直感的ではありません(全角だから？)

自分のユースケースでは、
自動予約で予約して録画したけど、つまらなかったから自動予約を解除しよう、
みたいなときに、目的の自動予約を探すのに手間取りました。
致命的に困ってるってわけではないですし、Ctrl-Fで探すという手もあるのですけどね。

探しやすくする案として、もっとも直近にヒットする番組日時順、
でソートできると探しやすいのではないか、と思いました。
ヘッダ部分がクリック出来て、好きな順でソートしなおせるとさらに完璧。
よろしければ検討おねがいします。

**Comment by kaikoma-soft** [comment]
タイトルの文字列のソートは単純に文字コードの大小で行っていますので、そういう物と諦めて下さい。
例えば漢数字の"一","二","三"は、"一","三","二" になったりしますし、1バイトの英数字と多バイトの英数字は見た目同じでも別物になります。

それで、自動予約一覧は私も前から気になっていたので、下記の機能追加をした Ver0.6.0 をリリースしましたので、お試し下さい。
 * 「自動予約一覧」で、項目のソート機能を追加。
 * 「予約一覧」の「自動」の項目をクリックして出る画面で、削除出来るようにした。

**Comment by yaminav** [comment]
> * 「自動予約一覧」で、項目のソート機能を追加。
> * 「予約一覧」の「自動」の項目をクリックして出る画面で、削除出来るようにした。

の動作を確認しました。自動予約が探しやすくなりました。ありがとうございます！

ちなみに、漢数字の文字コードが数字順に並んでない理由、は、部首や読みでソートされているから、だそうです。へー
https://blog.jnito.com/entry/2014/12/03/185146
