### ISSUE TITLE
番組表で、ツールチップの表示位置や大きさがおかしいことがある

### ISSUE THREAD

**Issue by yaminav** [kaikoma-soft/raspirec#9]
1. 番組表で、"1ページ当たりの放送局数(個)"の値を増やしたり、ブラウザウィンドウの横幅を小さくするなどして、ブラウザに横移動のスクロールバーがでるようにする
2. スクロールバーを操作し、右にスクロールさせる
3. 右にスクロールした先の場所にある番組をポイントする

と、表示されるツールチップの場所がおかしかったり、横幅が妙に小さく表示されたりします。

スクロールバーで番組は画面の中央に来ていても、それを認識できておらず、画面端にあるときのような挙動をしているように見えます。
問題が起きるのは横方向のスクロールさせた時だけで、縦方向のスクロールに関しては問題なさそう。

ブラウザはgoogle chrome バージョン: 90.0.4430.85（Official Build） （64 ビット）です。
Microsoft edgeでも同様の挙動でした。

**Comment by kaikoma-soft** [comment]
レポートありがとうございます。現象は確認出来ました。
仕掛中のものがあるので、すぐには出来ませんが将来的には対策したいと思います。
しばらくお待ち下さい。

**Comment by kaikoma-soft** [comment]
お待たせしました。修正をした Ver1.1.0 をリリースしましたので、ご確認下さい。

**Comment by yaminav** [comment]
修正確認しました。ありがとうございます！
